<?php

namespace bouquins\BackBundle\Entity;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAll()
    {
        $qb = $this->createQueryBuilder('c');

        $query = $qb;

        $result = $qb->getQuery()->execute();

        return $result;
    }

    public function getElementByName(Categorie $categorie)
    {
        $qb = $this->createQueryBuilder('c');
        $query = $qb
            ->where('c.nomCategorie = :nomCategorie')
            ->setParameter('nomCategorie',$categorie->getNomCategorie());
        $result = $qb->getQuery()->execute();

        return $result;
    }
}
