bouquins_front_homepage:
    path:     /
    defaults: { _controller: bouquinsFrontBundle:Default:index }

bouquins_front_register:
    path:     /register
    defaults: { _controller: bouquinsFrontBundle:Register:register }

bouquins_front_login:
    path:     /login
    defaults: { _controller: bouquinsFrontBundle:Login:login }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"